 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.4 Build 241129
//-----------------------------------------------------------------------------
#ifndef __GPIO_H
#define __GPIO_H

#include "ht32.h"

//-----------------------------------------------------------------------------


//-----------------------------------------------------------------------------
#define OUT_PA0_PORT           A
#define OUT_PA0_PIN            0
#define OUT_PA0_GPIO_CLK      STRCAT2(P,          OUT_PA0_PORT)
#define OUT_PA0_GPIO_ID       STRCAT2(GPIO_P,     OUT_PA0_PORT)
#define OUT_PA0_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PA0_PORT)
#define OUT_PA0_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PA0_PIN)
#define OUT_PA0_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PA0_HIGH          OUT_PA0_GPIO_PORT->SRR    = OUT_PA0_GPIO_PIN
#define OUT_PA0_LOW           OUT_PA0_GPIO_PORT->RR     = OUT_PA0_GPIO_PIN
#define OUT_PA0_XOR           OUT_PA0_GPIO_PORT->DOUTR ^= OUT_PA0_GPIO_PIN

#define OUT_PA8_PORT           A
#define OUT_PA8_PIN            8
#define OUT_PA8_GPIO_CLK      STRCAT2(P,          OUT_PA8_PORT)
#define OUT_PA8_GPIO_ID       STRCAT2(GPIO_P,     OUT_PA8_PORT)
#define OUT_PA8_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PA8_PORT)
#define OUT_PA8_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PA8_PIN)
#define OUT_PA8_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PA8_HIGH          OUT_PA8_GPIO_PORT->SRR    = OUT_PA8_GPIO_PIN
#define OUT_PA8_LOW           OUT_PA8_GPIO_PORT->RR     = OUT_PA8_GPIO_PIN
#define OUT_PA8_XOR           OUT_PA8_GPIO_PORT->DOUTR ^= OUT_PA8_GPIO_PIN

#define OUT_PA9_PORT           A
#define OUT_PA9_PIN            9
#define OUT_PA9_GPIO_CLK      STRCAT2(P,          OUT_PA9_PORT)
#define OUT_PA9_GPIO_ID       STRCAT2(GPIO_P,     OUT_PA9_PORT)
#define OUT_PA9_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PA9_PORT)
#define OUT_PA9_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PA9_PIN)
#define OUT_PA9_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PA9_HIGH          OUT_PA9_GPIO_PORT->SRR    = OUT_PA9_GPIO_PIN
#define OUT_PA9_LOW           OUT_PA9_GPIO_PORT->RR     = OUT_PA9_GPIO_PIN
#define OUT_PA9_XOR           OUT_PA9_GPIO_PORT->DOUTR ^= OUT_PA9_GPIO_PIN



//-----------------------------------------------------------------------------
void GPIO_Configuration(void);

#endif

